name: Generate Markdown File with Test Names

on:
  pull_request:
    types:
      - closed

jobs:
  generate_markdown:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          cd markdown
          npm install
          
      - name: Generate Markdown File
        run: node ./markdown/generate-markdown-file.js
        
      - name: Commit "Update tests.md"
        run: |
          git add .
          git config user.email github-actions@github.com
          git config user.name github-actions
          git commit -m "Update tests.md"
          
      - name: Push Changes to Master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
